export const data = [
  "Smoking, drinking and other drug consumption are strictly prohibited and necessary action will be taken by the institute if a participant or visitor is found to be in possession of these items.",
  "Any damage to institution facilities and property provided to the participants would result in serious action and necessary reimbursement charges would have to be dealt by the participants who are found guilty.",
  "The college will not be responsible for any damage or loss of property or valuables stored in places of accommodation.",
  "Upon check-out, the Guest should settle all the accounts with regard to the services rendered and return the receipt to the organizers.",
  "Participants should strictly follow the curfew timings of IIT Ropar .",
  "No outside vehicles will be allowed into the campus during Zeitgeist.",
  "Random checks would be made to avoid any illegal stay at the campus. Any team failing to produce their electronic/physical receipts of accommodation would be heavily fined and disqualified.",
  "Any attempt to enter into a prohibited area in the venue will lead to eviction from the venue.",
  "Tickets with tampered hologram and the tickets void of hologram or the official stamp and signature will be considered inadmissible.",
  "NO Cancellation policy. Requests for refund will not be entertained at any time or in any circumstances.",
  "We do not take responsibility for any material shown during a performance/act. Though we would try our best to ensure that all performances are respectful to every person present in the audience, it would be the responsibility of the performers if that isn't the case.",
  "We reserve the right to change, update, delete or add to the Terms at any time without notification to you. Any changes to the Terms will be effective immediately upon posting, and any continued use by you of the Website and/or the Services after changes have been posted constitute your acceptance to those changes.",
  "It is the responsibility of the participants to get themselves acquainted with the rules of each event. And the organizing team holds every right to disqualify participants in cases the rules are not followed or violated.",
  "The decision of the organizing team and judges in all events will be final.",
];